version: "3.9"

services:
  ywebsocket:
    image: node:20-alpine
    container_name: nodal-ywebsocket
    working_dir: /app
    command: sh -c "npm i -g y-websocket && y-websocket --port 3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3002:3002"

  lockws:
    image: node:20-alpine
    container_name: nodal-lockws
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "node /app/local-ws-server.js"
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    restart: unless-stopped


